/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
  export interface RouteNamedMap {
    '//exception/403': RouteRecordInfo<'//exception/403', '/exception/403', Record<never, never>, Record<never, never>>,
    '//exception/404': RouteRecordInfo<'//exception/404', '/exception/404', Record<never, never>, Record<never, never>>,
    '//exception/500': RouteRecordInfo<'//exception/500', '/exception/500', Record<never, never>, Record<never, never>>,
    '//login/': RouteRecordInfo<'//login/', '/login', Record<never, never>, Record<never, never>>,
    '//redirect/': RouteRecordInfo<'//redirect/', '/redirect', Record<never, never>, Record<never, never>>,
    '//system/menu/': RouteRecordInfo<'//system/menu/', '/system/menu', Record<never, never>, Record<never, never>>,
  }}
}
