name = "app"
main = "src/server.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ['nodejs_compat']

[triggers]
crons = []

[[d1_databases]]
binding = "DB"
database_name = "static"
database_id = "5a563d4c-6838-48e2-877e-5fcce505a028"
preview_database_id = "41bee6fa-aa39-4e58-9530-f818356f8337"

[placement]
mode = "smart"

[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 'static'
preview_bucket_name = 'preview-static'
